version: '3.8'

services:
  collector:
    build: ./collector
    container_name: collector
    networks:
      - app_network

  agent:
    build: ./agent
    container_name: agent
    depends_on:
      - collector
    networks:
      - app_network

  dashboard:
    build: ./dashboard
    container_name: dashboard
    depends_on:
      - collector
    ports:
      - "8050:8050"
    networks:
      - app_network

networks:
  app_network:
